
# configurations for our sayingFactory
helloapp:

  saying: ${HELLOAPP_SAYING:-Salam Kenal}


greeter:

  saying: ${GREETER_SAYING:-Salam dari Dropwizard}
  host: ${GREETER_BACKEND_HOST:-backend}
  port: ${GREETER_BACKEND_PORT:-80}

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
   